### PR TITLE
new cv.jit object for contour/convex hull analysis

### PR DESCRIPTION
**Pull request by ramagottfried**
I'd like to contribute a new object called `cv.jit.contours`, which provides contour and convex hull information in dictionary format. The object has been used in live performance already earlier this year, and seems stable. Please take a look, and let me know if there are any other steps I should take for testing etc.

best,
Rama

### CODE REVIEW

**Comment by tap** [comment]
Hi @ramagottfried -- Thanks for this!  

As you might be able to see from this Pull Request page, there appear to be some problems. At a minimum it looks like the `.def` files for all of the objects (not just yours) have had their line endings changed. As a result our continuous integration service can not build the package with this Pull Request.

If you would like clean this up so that it builds and the changes are limited to those required for the new object then we'd be happy to review for inclusion.

**Comment by ramagottfried** [comment]
hi @tap,
thanks! yes, the .def and .xcodeproj changes happened when I added my object to the build-all target in Xcode and Visual Studio. Is it possible that the problem is that I was using VS 2013 and you are on a different version?

I'll experiment with adding my object to a clean copy of the cycling repository.

best,
rama

**Comment by tap** [comment]
Hi @ramagottfried -- I'm going to go ahead and close this Pull Request and let you issue a new one when you're ready. Hope that helps!

**Comment by ramagottfried** [comment]
Hi @tap -- ok thanks, sounds good. I decided to tweak a few things in the meantime -- hoping to have a revised version ready for release in the not too distant future.

**Pull request closed without merging**
